export const SET_FIELD_VALUE = 'SET_FIELD_VALUE';
export const SET_FIELD_TOUCHED = 'SET_FIELD_TOUCHED';
export const SET_ERRORS = 'SET_ERRORS';
export const SUBMIT_ATTEMPT = 'SUBMIT_ATTEMPT';
export const SUBMIT_SUCCESS = 'SUBMIT_SUCCESS';
export const SUBMIT_FAILURE = 'SUBMIT_FAILURE';
